### ISSUE TITLE
scikit-image version

### ISSUE THREAD

**Issue by udifuchs** [ziatdinovmax/GPim#32]
The requirement for `scikit-image==0.16.2` seems too harsh.
Can you replace it with `scikit-image>=0.16.2`?

**Comment by ziatdinovmax** [comment]
Yes, this was supposed to be a temporary solution  to deal with some issues in Python<=3.6.  I need to update a setup file and also replace Travis CI with GitHub workflows.

**Comment by ziatdinovmax** [comment]
close via #33
